esphome:
  name: ai_think03
  platform: ESP32
  board: esp32cam

wifi:
  ssid:     !secret wifi_ssid
  password: !secret wifi_pass
  power_save_mode: HIGH

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ai Think03 Fallback Hotspot"
    password: "etjha39it9"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_passwd
  
ota:
  password: !secret ota_passwd



# Example configuration entry
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  # Image settings
  name: cam03
  # resolution: 1280x1024
  resolution: 1024x768

  
  # Flashlight
output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4
light:
  - platform: binary
    output: gpio_4
    name: cam03 light
