
substitutions:
  devicename: bathroom_1
  upper_devicename: Iron 1

esphome:
  platform: ESP8266
  name: $devicename
  board: esp8285
  arduino_version: 2.4.2
  
wifi:
  ssid:     !secret wifi_ssid
  password: !secret wifi_pass
  # use_address:  test01.local
  power_save_mode: HIGH
  manual_ip:
    static_ip: 192.168.1.65
    gateway: 192.168.1.254
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_passwd
  
ota:
  password: !secret ota_passwd

  

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Bathroom 1 Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Bathroom 1 Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
    
sensor:
  - platform: wifi_signal
    name: "Bathroom 1 WiFi Sensor"
    update_interval: 60s
    
  - platform: dht
    model: DHT11
    pin:
      number: GPIO14
      mode: INPUT
    temperature:
      name: "Bathroom Room Temperature"
    humidity:
      name: "Bathroom Room Humidity"
    update_interval: 30s