esphome:
  name: rf1
  platform: ESP8266
  board: esp01_1m

  libraries:
    - "ESPiLight"

wifi:
  ssid:     !secret wifi_ssid
  password: !secret wifi_pass
  manual_ip:
    static_ip: 192.168.1.64
    gateway: 192.168.1.254
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_passwd
  
ota:
  password: !secret ota_passwd


web_server:
  port: 80

binary_sensor:
  - platform: status
    name: "RF Bridge Status"


# remote_receiver:
#   pin: 4
#   dump: all
#   # filter: 200 # I found, that smaller values works much better, so...
#   filter: 2us
#   idle: 2ms

# rf_espilight:
#   pin: 4
#   dump: all
#   # filter: 200 # I found, that smaller values works much better, so...
#   filter: 2us
#   idle: 2ms

andrea:
  pin: 4

remote_transmitter:
  pin: 5
  carrier_duty_percent: 100%

status_led:
  pin:
    number: GPIO13
    inverted: yes

